name: Check pull request description checkbox
description: "Validate if a specific checkbox in a pull request description is checked or not."

branding:
  icon: "award"
  color: "green"

inputs:
  checkbox:
    description: "The name of the checkbox to verify"
    required: true
    default: "Integration test (Mandatory)"

runs:
  using: "composite"
  steps:
    - name: Check pull request description
      env:
        BODY: ${{ github.event.pull_request.body }}
        CHECKBOX: ${{ inputs.checkbox }}
      run: |
        echo "$BODY"
        echo "$CHECKBOX"
        CHECK_STRING="- [x] Integration test (Mandatory)"
        if echo "$BODY" | grep -q "$CHECK_STRING"; then
          echo "Checkbox is checked"
          exit 0
        else
          echo "Checkbox is not checked"
          exit 1
        fi
