name: Check pull request description checkbox
description: "Validate if a specific checkbox in a pull request description is checked or not."

branding:
  icon: "award"
  color: "green"

inputs:
  checkbox:
    description: "The name of the checkbox to verify"
    required: true
    default: "Integration test (Mandatory)"

runs:
  using: "composite"
  steps:
    - name: Check pull request description
      env:
        BODY: ${{ github.event.pull_request.body }}
        CHECKBOX: ${{ inputs.checkbox }}
      shell: bash
      run: |
        CHECKED="\[x\] $CHECKBOX"
        UNCHECKED="\[ \] $CHECKBOX"
        if echo "$BODY" | grep -q "$CHECKED"; then
          echo "Checkbox is checked"
          exit 0
        elif echo "$BODY" | grep -q "$UNCHECKED"; then
          echo "Checkbox is not checked"
          exit 1
        else
          echo "Checkbox not found in pull request description"
          exit 1
        fi
